"""Constants for the GE-Spot integration."""

from .config import (
    CONF_SOURCE,
    CONF_AREA,
    CONF_VAT,
    CONF_UPDATE_INTERVAL,
    CONF_DISPLAY_UNIT,
    CONF_ENABLE_FALLBACK,
    CONF_CURRENCY,
    CONF_PRECISION,
    CONF_API_KEY,
    CONF_PRICE_IN_CENTS,
    CONF_CACHE_TTL,
    CONF_SOURCE_PRIORITY,
    Config
)

from .defaults import (
    DEFAULT_NAME,
    DEFAULT_VAT,
    DEFAULT_UPDATE_INTERVAL,
    DEFAULT_DISPLAY_UNIT,
    DEFAULT_ENABLE_FALLBACK,
    DEFAULT_PRECISION,
    DEFAULT_CACHE_TTL,
    Defaults
)

from .sources import (
    SOURCE_ENERGI_DATA_SERVICE,
    SOURCE_NORDPOOL,
    SOURCE_ENTSO_E,
    SOURCE_EPEX,
    SOURCE_OMIE,
    SOURCE_AEMO,
    SOURCES,
    Source
)

from .areas import (
    AREA_TIMEZONES,
    ENTSOE_AREA_MAPPING,
    ENTSOE_AREAS,
    NORDPOOL_AREAS,
    ENERGI_DATA_AREAS,
    EPEX_AREAS,
    OMIE_AREAS,
    AEMO_AREAS,
    DEFAULT_AREAS,
    NORDPOOL_DELIVERY_AREA_MAPPING
)

from .currencies import (
    REGION_TO_CURRENCY,
    CURRENCY_SUBUNIT_MULTIPLIER,
    CURRENCY_SUBUNIT_NAMES,
    ENERGY_UNIT_CONVERSION
)

from .display import (
    DISPLAY_UNIT_DECIMAL,
    DISPLAY_UNIT_CENTS,
    DISPLAY_UNITS,
    UPDATE_INTERVAL_OPTIONS
)

from .sensors import (
    SENSOR_TYPE_CURRENT,
    SENSOR_TYPE_NEXT,
    SENSOR_TYPE_DAY_AVG,
    SENSOR_TYPE_PEAK,
    SENSOR_TYPE_OFF_PEAK,
    SENSOR_TYPE_TOMORROW_AVG,
    SENSOR_TYPE_TOMORROW_PEAK,
    SENSOR_TYPE_TOMORROW_OFF_PEAK,
    SensorType
)

from .attributes import (
    ATTR_DATA_SOURCE,
    ATTR_FALLBACK_USED,
    ATTR_RAW_API_DATA,
    ATTR_RAW_VALUES,
    ATTR_FALLBACK_INFO,
    ATTR_USING_CACHED_DATA,
    ATTR_ATTEMPTED_SOURCES,
    ATTR_PRIMARY_SOURCE,
    ATTR_ACTIVE_SOURCE,
    ATTR_RAW_VALUE,
    ATTR_CONVERSION_INFO,
    ATTR_CURRENCY,
    ATTR_AREA,
    ATTR_VAT,
    ATTR_TODAY,
    ATTR_TOMORROW,
    ATTR_TOMORROW_VALID,
    ATTR_RAW_TODAY,
    ATTR_RAW_TOMORROW,
    ATTR_CURRENT_PRICE,
    ATTR_MIN,
    ATTR_MAX,
    ATTR_AVERAGE,
    ATTR_OFF_PEAK_1,
    ATTR_OFF_PEAK_2,
    ATTR_PEAK,
    ATTR_LAST_UPDATED,
    ATTR_AVAILABLE_FALLBACKS,
    ATTR_IS_USING_FALLBACK,
    ATTR_API_KEY_STATUS,
    Attributes
)

from .errors import (
    ErrorMessages,
    TRANSLATIONS
)

# Domain
DOMAIN = "ge_spot"
