"""Configuration constants for GE-Spot integration."""

class Config:
    """Configuration constants."""
    SOURCE = "source"
    AREA = "area"
    VAT = "vat"
    UPDATE_INTERVAL = "update_interval"
    DISPLAY_UNIT = "display_unit"
    CURRENCY = "currency"
    PRECISION = "precision"
    API_KEY = "api_key"
    PRICE_IN_CENTS = "price_in_cents"
    CACHE_TTL = "cache_ttl"
    SOURCE_PRIORITY = "source_priority"
    ORIGINAL_AREA = "original_area"
