version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github_actions"
    commit-message:
      prefix: "GitHub Actions"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:15"
      timezone: "UTC"
    open-pull-requests-limit: 10
    groups:
      python-runtime:
        patterns:
          - "aiohttp"
          - "aiofiles"
          - "beautifulsoup4"
          - "PyJWT"
          - "voluptuous"
          - "xmltodict"
      python-tooling:
        patterns:
          - "freezegun"
          - "homeassistant"
          - "pytest-homeassistant-custom-component"
          - "pytz"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "Python"
    target-branch: "main"
    versioning-strategy: increase-if-necessary
